spring.application.name=shape-management-appliaction-api

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/shape-management?createDatabaseIfNotExist=true}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:password}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true

jwt.secret=247b76761752ba404f5c5e098a04c1f4f5c31290c6cd799623d69dc38a762e02
jwt.expiration=3600000