spring.application.name=shape-management-appliaction-api

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/shape-management?createDatabaseIfNotExist=true}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:password}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true

# JWT config
jwt.secret=58e3dd8cd10f62e87254cdee50360e24492ff2338407e4a13bb6c14e4848d35f
jwt.access-token.expiration=3600000
jwt.refresh-token.expiration=604800000

logging.level.com.spillabs=DEBUG
org.springframework.security=DEBUG